"""initial_sqlite

Revision ID: 3e2d31dee58c
Revises: 
Create Date: 2026-09-03 11:11:21.758345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2d31dee58c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'mapped', 'cleaned', 'ready', name='datasetstatus'), nullable=False),
    sa.Column('detected_columns', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_user_id'), 'datasets', ['user_id'], unique=False)
    op.create_table('column_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=255), nullable=True),
    sa.Column('unit_price', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.String(length=255), nullable=True),
    sa.Column('discount', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_mappings_dataset_id'), 'column_mappings', ['dataset_id'], unique=True)
    op.create_table('data_quality_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('missing_values_count', sa.Integer(), nullable=False),
    sa.Column('invalid_date_count', sa.Integer(), nullable=False),
    sa.Column('invalid_quantity_count', sa.Integer(), nullable=False),
    sa.Column('invalid_price_count', sa.Integer(), nullable=False),
    sa.Column('outlier_count', sa.Integer(), nullable=False),
    sa.Column('missing_customer_id', sa.Integer(), nullable=False),
    sa.Column('missing_product', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('column_stats', sa.JSON(), nullable=True),
    sa.Column('cleaning_log', sa.JSON(), nullable=True),
    sa.Column('user_attention_items', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_reports_dataset_id'), 'data_quality_reports', ['dataset_id'], unique=True)
    op.create_table('mining_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('rfm_segments', sa.JSON(), nullable=True),
    sa.Column('customer_clusters', sa.JSON(), nullable=True),
    sa.Column('association_rules', sa.JSON(), nullable=True),
    sa.Column('sales_patterns', sa.JSON(), nullable=True),
    sa.Column('anomalies', sa.JSON(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mining_results_dataset_id'), 'mining_results', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mining_results_dataset_id'), table_name='mining_results')
    op.drop_table('mining_results')
    op.drop_index(op.f('ix_data_quality_reports_dataset_id'), table_name='data_quality_reports')
    op.drop_table('data_quality_reports')
    op.drop_index(op.f('ix_column_mappings_dataset_id'), table_name='column_mappings')
    op.drop_table('column_mappings')
    op.drop_index(op.f('ix_datasets_user_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
